### ISSUE TITLE
Get travis-ci working

### ISSUE THREAD

**Issue by padilla410** [LimnoTech/limnotools#1]
travis CI does not currently work

**Comment by padilla410** [comment]
Contact TAS

**Comment by aufdenkampe** [comment]
@padilla410, nice work on this, and kudos for wanting to set up Travis-CI!

**Comment by padilla410** [comment]
It has been working well on the RNERRS project, but I'm managing that one on my personal acct (hence I have access to all of my repositories via travis-CI). Have you used it at all on group projects? Does the "limnotech" owner have to set it up?

**Comment by aufdenkampe** [comment]
The groups that I lead do use travis-CI on many of our repos. However, I haven't done this myself (other team members have). It makes sense that there might be a permissions issue blocking you from doing it under the LimnoTech GitHub organization. Let me know if you would like me to help looking into that.

**Comment by aufdenkampe** [comment]
@LimnoTech/r-developers, I just added this repo to our renamed group, and gave everyone in the group Admin permissions. Let's see if that does it.

**Comment by aufdenkampe** [comment]
@padilla410, I just granted "Third-party access" to Travis-CI. Let me know if this does it.

**Comment by tslawecki** [comment]
I did get an email from GitHub asking me to approve, so I did after seeing this thread.

**Comment by aufdenkampe** [comment]
Perfect! Thanks @tslawecki

**Comment by tslawecki** [comment]
Guessing we got the same notice, I think you're also an administrator.

**Comment by aufdenkampe** [comment]
Yes. You assigned me as a co- "Owner" when I arrived, which has been great. Thanks.
Hua, Todd and LimnoTech-m are also Owners. https://github.com/orgs/LimnoTech/people

**Comment by padilla410** [comment]
I successfully ran Travis-CI on the limnotools repository
